language: node_js
sudo: false
node_js:
  - "12.9.1"
install:
  - npm install
script:
  - npm run test
notifications:
  email: false
env:
  global:
    MONGODB_URL=mongodb+srv://swapnilgmail:2c5zlIFAVkCLxCrn@cluster0-qvncy.mongodb.net/test?retryWrites=true&w=majority
